export const TODOIST_API_BASE_URL = Cypress.env('TODOIST_API_BASE_URL')
export const TODOIST_API_TOKEN = Cypress.env('TODOIST_API_TOKEN')
export const TODOIST_WEB_BASE_URL = Cypress.env('TODOIST_WEB_BASE_URL')
export const TODOIST_USERNAME = Cypress.env('TODOIST_USERNAME')
export const TODOIST_PASSWORD = Cypress.env('TODOIST_PASSWORD')
